* ===========================================================================
* config.do  --  single path configuration for the replication archive.
*
* HOW TO RUN: from a Stata session whose working directory is `code/`, first
*     do "config.do"
* then run any pipeline script (also from `code/`), e.g. `do build/UIMacro_BuildData.do`.
* Each pipeline script re-runs this file itself, so you can also run them directly
* from `code/`. EDIT THE ONE LINE below to this archive's location on your machine.
* ===========================================================================

global root "~/Dropbox/UI_ReplicationKit"          //  <-- EDIT: path to this archive

* --- derived locations (do not edit) ---
global code          "${root}/code"
global rawdata       "${root}/data/raw"
global processed     "${root}/data/processed"
global output        "${root}/output"
global tables        "${output}/tables"
global figures       "${output}/figures"
global factor_csv    "${output}/factor_results"      // analysis/Matlab result CSVs (make_tables reads)
global factor_inputs "${output}/factor_inputs"       // per-pair QBLS handoff (regenerated by exporters)
global synthetic     "${root}/synthetic-data"

* --- analysis convenience: cd "${maindirectory}"; use "${CurrentData}" / "${DataControls}.dta" ---
global maindirectory "${processed}/"
global CurrentData   "UIMacro_RevisionData.dta"
global DataControls  "UIMacro_DataControls"
global Wages         "ProcessedWages.dta"
global outdirectory  "${factor_inputs}/"             // exporters write QBLS here
global latexdir      "${factor_csv}/"                // analysis/Matlab result CSVs (make_tables reads)

* --- vacancy data switch ---------------------------------------------------
* vacfile/statefile are the two PROVIDED synthetic stand-ins for the proprietary HWOL
* inputs (synthetic-data/; the confidential HWOL data are NOT in this archive). To reproduce the PUBLISHED (HWOL)
* vacancy numbers, the Data Editor replaces these two files with the licensed Conference
* Board HWOL data and re-runs. See code/build/SYNTHETIC_VACANCY_PATH.md.
global vacfile      "${synthetic}/new_vac_synthetic.dta"
global statefile    "${synthetic}/StateMonthlyBorderData_synthetic.dta"
* ImputedDataBorder is a BUILT intermediate, NOT shipped: the replicator generates it by
* running the imputation (analysis/Impute_Input.do -> matlab/Run_Impute_Border.m ->
* analysis/Impute_to_Stata.do) on ${vacfile}; it lands in data/processed/ (synthetic by
* default, the real version if the Data Editor swaps in HWOL).
global ImputedFile  "${processed}/ImputedDataBorder.dta"

* --- figure styling: the published figures were drawn under the classic
* s2color scheme; Stata 18+ defaults to stcolor, which changes gridlines,
* markers, and legend styling. Pin the scheme so regenerated figures match.
cap set scheme s2color

* ensure the built-output folders exist (the archive ships them empty / absent)
cap mkdir "${processed}"
cap mkdir "${output}"
cap mkdir "${tables}"
cap mkdir "${figures}"
cap mkdir "${factor_csv}"
cap mkdir "${factor_inputs}"

local ssc_packages "reghdfe binscatter regife outreg2 ftools coefplot tuples hdfe mat2txt ivreg2 ranktest"
if !missing("`ssc_packages'") { 
	foreach pkg in `ssc_packages' {
		capture which `pkg' 
		if _rc == 111 {
			dis "Installing `pkg'"
			ssc install `pkg', replace
			}
		which `pkg' 
		}
}
